// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCpkw0dahd0wYMYqnbANiaWKBgUf-8zVw',
    appId: '1:334860684228:web:f6b82fa700fa44440ef291',
    messagingSenderId: '334860684228',
    projectId: 'labassignment-ict602',
    authDomain: 'labassignment-ict602.firebaseapp.com',
    storageBucket: 'labassignment-ict602.firebasestorage.app',
    measurementId: 'G-Y3CPZ0C8NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPhJn75M5DeCP0zbpRQ1KV2IVVn4fYXk',
    appId: '1:334860684228:android:6d8e2de54a071a120ef291',
    messagingSenderId: '334860684228',
    projectId: 'labassignment-ict602',
    storageBucket: 'labassignment-ict602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc29rg99uUsfDiVmLZDIbKd4GIDTTeIYI',
    appId: '1:334860684228:ios:8a2792345c3ef41c0ef291',
    messagingSenderId: '334860684228',
    projectId: 'labassignment-ict602',
    storageBucket: 'labassignment-ict602.firebasestorage.app',
    iosBundleId: 'com.example.ict602Assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc29rg99uUsfDiVmLZDIbKd4GIDTTeIYI',
    appId: '1:334860684228:ios:8a2792345c3ef41c0ef291',
    messagingSenderId: '334860684228',
    projectId: 'labassignment-ict602',
    storageBucket: 'labassignment-ict602.firebasestorage.app',
    iosBundleId: 'com.example.ict602Assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCpkw0dahd0wYMYqnbANiaWKBgUf-8zVw',
    appId: '1:334860684228:web:dcc4836170a208bd0ef291',
    messagingSenderId: '334860684228',
    projectId: 'labassignment-ict602',
    authDomain: 'labassignment-ict602.firebaseapp.com',
    storageBucket: 'labassignment-ict602.firebasestorage.app',
    measurementId: 'G-15G1TKE6Z0',
  );
}
